# Generated by Django 3.0.4 on 2020-03-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_lei', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('series_name', models.CharField(max_length=256)),
                ('rep_pd_date', models.DateField()),
                ('total_assets', models.FloatField()),
                ('total_liabilities', models.FloatField()),
                ('net_assets', models.FloatField()),
            ],
        ),
    ]
